default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: postgres

test:
  <<: *default
  database: bookstore

development:
  <<: *default
  database: bookstore

production:
  <<: *default
  database: bookstore
